server:
  #端口号
  port: 8082
  servlet:
    #上下文根
    context-path: /

spring:
  #配置数据库连接信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sec?characterEncoding=utf8&useSSL=false
    username: root
    password: tian

  #配置redis
  redis:
    host: 192.168.117.129
    port: 6379
#配置dubbo
dubbo:
  application:
    name: annotation-consumer
  registry:
    address: zookeeper://192.168.117.129:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.tian.service.impl

#配置mybatis_plus表缀
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_